!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.15 (master) - 15 Apr 2020 13:12
!
MODULE FORWARD_DIFF
  IMPLICIT NONE
  REAL*8, PARAMETER :: xend=30
  REAL*8, PARAMETER :: dx=1
  INTEGER, PARAMETER :: nx=INT(xend/dx)

CONTAINS
!  Differentiation of forward_problem in forward (tangent) mode:
!   variations   of useful results: v
!   with respect to varying inputs: xx
!   RW status of diff variables: v:out xx:in
  SUBROUTINE FORWARD_PROBLEM_D(xx, xxd, v, vd)
    IMPLICIT NONE
    REAL*8, PARAMETER :: rho=920.0
    REAL*8, PARAMETER :: g=9.2
    REAL*8, PARAMETER :: n=3
    REAL*8, PARAMETER :: a=1e-16
    REAL*8, PARAMETER :: dt=1/12.0
    REAL*8, PARAMETER :: c=2*a/(n+2)*(rho*g)**n*1.e3**n
    REAL*8, PARAMETER :: tend=5000
    REAL*8, PARAMETER :: bx=-0.0001
    REAL*8, PARAMETER :: m0=.004, m1=0.0002
    INTRINSIC INT
    INTEGER, PARAMETER :: nt=INT(tend/dt)
    REAL*8, DIMENSION(nx+1, nt+1) :: h
    REAL*8, DIMENSION(nx+1, nt+1) :: hd
    REAL*8, DIMENSION(nx+1, nt+1) :: h_capital
    REAL*8, DIMENSION(nx+1, nt+1) :: h_capitald
    INTEGER :: t, i
    REAL*8, DIMENSION(nx+1) :: xarr
    REAL*8, DIMENSION(nx+1) :: m
    REAL*8, DIMENSION(nx+1) :: md
    REAL*8, DIMENSION(nx+1) :: b
    REAL*8, DIMENSION(nx) :: d, phi
    REAL*8, DIMENSION(nx) :: dd, phid
    REAL*8, DIMENSION(nx+1), INTENT(IN) :: xx
    REAL*8, DIMENSION(nx+1), INTENT(IN) :: xxd
    REAL*8, INTENT(OUT) :: v
    REAL*8, INTENT(OUT) :: vd
    INTRINSIC SIZE
    REAL*8, DIMENSION(nx) :: pwx1
    REAL*8, DIMENSION(nx) :: pwx1d
    REAL*8 :: pwy1
    REAL*8, DIMENSION(nx) :: pwr1
    REAL*8, DIMENSION(nx) :: pwr1d
    REAL*8, DIMENSION(nx) :: pwx2
    REAL*8, DIMENSION(nx) :: pwx2d
    REAL*8 :: pwy2
    REAL*8, DIMENSION(nx) :: pwr2
    REAL*8, DIMENSION(nx) :: pwr2d
    REAL*8, DIMENSION(nx) :: temp
    m = (/(m0-(i-1)*dx*m1, i=1,nx+1)/)
    b = (/(1.0+bx*(i-1)*dx, i=1,nx+1)/)
    md = xxd
    m = m + xx
    h(1, :) = b(1)
    h(:, 1) = b
    h(nx+1, :) = b(nx+1)
    h_capital(1, :) = h(1, :) - b(1)
    h_capital(nx+1, :) = h(nx+1, :) - b(nx+1)
    h_capital(:, 1) = h(:, 1) - b
    h_capitald = 0.0_8
    hd = 0.0_8
    DO t=1,nt
      pwx1d = (h_capitald(1:nx, t)+h_capitald(2:nx+1, t))/2
      pwx1 = (h_capital(1:nx, t)+h_capital(2:nx+1, t))/2
      pwy1 = n + 2
      WHERE (pwx1 .LE. 0.0 .AND. (pwy1 .EQ. 0.0 .OR. pwy1 .NE. INT(pwy1)&
&         )) 
        pwr1d = 0.0_8
      ELSEWHERE
        pwr1d = pwy1*pwx1**(pwy1-1)*pwx1d
      END WHERE
      pwr1 = pwx1**pwy1
      pwx2d = (hd(2:nx+1, t)-hd(1:nx, t))/dx
      pwx2 = (h(2:nx+1, t)-h(1:nx, t))/dx
      pwy2 = n - 1
      WHERE (pwx2 .LE. 0.0 .AND. (pwy2 .EQ. 0.0 .OR. pwy2 .NE. INT(pwy2)&
&         )) 
        pwr2d = 0.0_8
      ELSEWHERE
        pwr2d = pwy2*pwx2**(pwy2-1)*pwx2d
      END WHERE
      pwr2 = pwx2**pwy2
      dd(:) = c*(pwr2*pwr1d+pwr1*pwr2d)
      d(:) = c*pwr1*pwr2
      temp = h(2:nx+1, t) - h(1:nx, t)
      phid(:) = -(temp*dd(:)/dx+d(:)*(hd(2:nx+1, t)-hd(1:nx, t))/dx)
      phi(:) = -(d(:)/dx*temp)
      hd(2:nx, t+1) = hd(2:nx, t) + dt*md(2:nx) - dt*(phid(2:nx)-phid(1:&
&       nx-1))/dx
      h(2:nx, t+1) = h(2:nx, t) + m(2:nx)*dt - dt/dx*(phi(2:nx)-phi(1:nx&
&       -1))
      WHERE (h(:, t+1) .LT. b) 
        hd(:, t+1) = 0.0_8
        h(:, t+1) = b
      END WHERE
      h_capitald(:, t+1) = hd(:, t+1)
      h_capital(:, t+1) = h(:, t+1) - b
    END DO
    vd = 0.0_8
    DO i=1,SIZE(h_capital(:, nt+1))
      vd = vd + dx*h_capitald(i, nt+1)
    END DO
  END SUBROUTINE FORWARD_PROBLEM_D

!  Differentiation of forward_problem in reverse (adjoint) mode:
!   gradient     of useful results: v
!   with respect to varying inputs: xx
!   RW status of diff variables: v:in-killed xx:out
  SUBROUTINE FORWARD_PROBLEM_B(xx, xxb, v, vb)
    IMPLICIT NONE
    REAL*8, PARAMETER :: rho=920.0
    REAL*8, PARAMETER :: g=9.2
    REAL*8, PARAMETER :: n=3
    REAL*8, PARAMETER :: a=1e-16
    REAL*8, PARAMETER :: dt=1/12.0
    REAL*8, PARAMETER :: c=2*a/(n+2)*(rho*g)**n*1.e3**n
    REAL*8, PARAMETER :: tend=5000
    REAL*8, PARAMETER :: bx=-0.0001
    REAL*8, PARAMETER :: m0=.004, m1=0.0002
    INTRINSIC INT
    INTEGER, PARAMETER :: nt=INT(tend/dt)
    REAL*8, DIMENSION(nx+1, nt+1) :: h
    REAL*8, DIMENSION(nx+1, nt+1) :: hb
    REAL*8, DIMENSION(nx+1, nt+1) :: h_capital
    REAL*8, DIMENSION(nx+1, nt+1) :: h_capitalb
    INTEGER :: t, i
    REAL*8, DIMENSION(nx+1) :: xarr
    REAL*8, DIMENSION(nx+1) :: m
    REAL*8, DIMENSION(nx+1) :: mb
    REAL*8, DIMENSION(nx+1) :: b
    REAL*8, DIMENSION(nx) :: d, phi
    REAL*8, DIMENSION(nx) :: db, phib
    REAL*8, DIMENSION(nx+1), INTENT(IN) :: xx
    REAL*8, DIMENSION(nx+1) :: xxb
    REAL*8 :: v
    REAL*8 :: vb
    INTRINSIC SIZE
    REAL*8, DIMENSION(nx) :: pwx1
    REAL*8, DIMENSION(nx) :: pwx1b
    REAL*8 :: pwy1
    REAL*8, DIMENSION(nx) :: pwr1
    REAL*8, DIMENSION(nx) :: pwr1b
    REAL*8, DIMENSION(nx) :: pwx2
    REAL*8, DIMENSION(nx) :: pwx2b
    REAL*8 :: pwy2
    REAL*8, DIMENSION(nx) :: pwr2
    REAL*8, DIMENSION(nx) :: pwr2b
    REAL*8, DIMENSION(nx) :: tempb
    REAL*8, DIMENSION(nx-1) :: tempb0
    INTEGER :: ad_to
    m = (/(m0-(i-1)*dx*m1, i=1,nx+1)/)
    b = (/(1.0+bx*(i-1)*dx, i=1,nx+1)/)
    m = m + xx
    h(1, :) = b(1)
    h(:, 1) = b
    h(nx+1, :) = b(nx+1)
    h_capital(1, :) = h(1, :) - b(1)
    h_capital(nx+1, :) = h(nx+1, :) - b(nx+1)
    h_capital(:, 1) = h(:, 1) - b
    DO t=1,nt
      CALL PUSHREAL8ARRAY(pwx1, nx)
      pwx1 = (h_capital(1:nx, t)+h_capital(2:nx+1, t))/2
      pwy1 = n + 2
      pwr1 = pwx1**pwy1
      CALL PUSHREAL8ARRAY(pwx2, nx)
      pwx2 = (h(2:nx+1, t)-h(1:nx, t))/dx
      pwy2 = n - 1
      pwr2 = pwx2**pwy2
      d(:) = c*pwr1*pwr2
      phi(:) = -(d(:)*(h(2:nx+1, t)-h(1:nx, t))/dx)
      CALL PUSHREAL8ARRAY(h(2:nx, t+1), nx - 1)
      h(2:nx, t+1) = h(2:nx, t) + m(2:nx)*dt - dt/dx*(phi(2:nx)-phi(1:nx&
&       -1))
      CALL PUSHREAL8ARRAY(h(:, t+1), nx + 1)
      WHERE (h(:, t+1) .LT. b) h(:, t+1) = b
      h_capital(:, t+1) = h(:, t+1) - b
    END DO
    DO i=1,SIZE(h_capital(:, nt+1))

    END DO
    ad_to = i - 1
    h_capitalb = 0.0_8
    DO i=ad_to,1,-1
      h_capitalb(i, nt+1) = h_capitalb(i, nt+1) + dx*vb
    END DO
    hb = 0.0_8
    mb = 0.0_8
    DO t=nt,1,-1
      hb(:, t+1) = hb(:, t+1) + h_capitalb(:, t+1)
      h_capitalb(:, t+1) = 0.0_8
      CALL POPREAL8ARRAY(h(:, t+1), nx + 1)
      pwy1 = n + 2
      pwr1 = pwx1**pwy1
      pwy2 = n - 1
      pwr2 = pwx2**pwy2
      d(:) = c*pwr1*pwr2
      phib = 0.0_8
      CALL POPREAL8ARRAY(h(2:nx, t+1), nx - 1)
      db = 0.0_8
      pwr1b = 0.0_8
      pwr2b = 0.0_8
      pwx2b = 0.0_8
      pwx1b = 0.0_8
      WHERE (h(:, t+1) .LT. b) hb(:, t+1) = 0.0_8
      hb(2:nx, t) = hb(2:nx, t) + hb(2:nx, t+1)
      mb(2:nx) = mb(2:nx) + dt*hb(2:nx, t+1)
      tempb0 = -(dt*hb(2:nx, t+1)/dx)
      hb(2:nx, t+1) = 0.0_8
      phib(2:nx) = phib(2:nx) + tempb0
      phib(1:nx-1) = phib(1:nx-1) - tempb0
      db(:) = -((h(2:nx+1, t)-h(1:nx, t))*phib(:)/dx)
      tempb = -(d(:)*phib(:)/dx)
      hb(2:nx+1, t) = hb(2:nx+1, t) + tempb
      hb(1:nx, t) = hb(1:nx, t) - tempb
      pwr1b = pwr2*c*db(:)
      pwr2b = pwr1*c*db(:)
      WHERE (pwx2 .LE. 0.0 .AND. (pwy2 .EQ. 0.0 .OR. pwy2 .NE. INT(pwy2)&
&         )) 
        pwx2b = 0.0_8
      ELSEWHERE
        pwx2b = pwy2*pwx2**(pwy2-1)*pwr2b
      END WHERE
      CALL POPREAL8ARRAY(pwx2, nx)
      hb(2:nx+1, t) = hb(2:nx+1, t) + pwx2b/dx
      hb(1:nx, t) = hb(1:nx, t) - pwx2b/dx
      WHERE (pwx1 .LE. 0.0 .AND. (pwy1 .EQ. 0.0 .OR. pwy1 .NE. INT(pwy1)&
&         )) 
        pwx1b = 0.0_8
      ELSEWHERE
        pwx1b = pwy1*pwx1**(pwy1-1)*pwr1b
      END WHERE
      CALL POPREAL8ARRAY(pwx1, nx)
      h_capitalb(1:nx, t) = h_capitalb(1:nx, t) + pwx1b/2
      h_capitalb(2:nx+1, t) = h_capitalb(2:nx+1, t) + pwx1b/2
    END DO
    xxb = 0.0_8
    xxb = mb
  END SUBROUTINE FORWARD_PROBLEM_B

  SUBROUTINE FORWARD_PROBLEM(xx, v)
    IMPLICIT NONE
    REAL*8, PARAMETER :: rho=920.0
    REAL*8, PARAMETER :: g=9.2
    REAL*8, PARAMETER :: n=3
    REAL*8, PARAMETER :: a=1e-16
    REAL*8, PARAMETER :: dt=1/12.0
    REAL*8, PARAMETER :: c=2*a/(n+2)*(rho*g)**n*1.e3**n
    REAL*8, PARAMETER :: tend=5000
    REAL*8, PARAMETER :: bx=-0.0001
    REAL*8, PARAMETER :: m0=.004, m1=0.0002
    INTRINSIC INT
    INTEGER, PARAMETER :: nt=INT(tend/dt)
    REAL*8, DIMENSION(nx+1, nt+1) :: h
    REAL*8, DIMENSION(nx+1, nt+1) :: h_capital
    INTEGER :: t, i
    REAL*8, DIMENSION(nx+1) :: xarr
    REAL*8, DIMENSION(nx+1) :: m
    REAL*8, DIMENSION(nx+1) :: b
    REAL*8, DIMENSION(nx) :: d, phi
    REAL*8, DIMENSION(nx+1), INTENT(IN) :: xx
    REAL*8, INTENT(OUT) :: v
    INTRINSIC SIZE
    REAL*8, DIMENSION(nx) :: pwx1
    REAL*8 :: pwy1
    REAL*8, DIMENSION(nx) :: pwr1
    REAL*8, DIMENSION(nx) :: pwx2
    REAL*8 :: pwy2
    REAL*8, DIMENSION(nx) :: pwr2
    xarr = (/((i-1)*dx, i=1,nx+1)/)
    m = (/(m0-(i-1)*dx*m1, i=1,nx+1)/)
    b = (/(1.0+bx*(i-1)*dx, i=1,nx+1)/)
    m = m + xx
    h(1, :) = b(1)
    h(:, 1) = b
    h(nx+1, :) = b(nx+1)
    h_capital(1, :) = h(1, :) - b(1)
    h_capital(nx+1, :) = h(nx+1, :) - b(nx+1)
    h_capital(:, 1) = h(:, 1) - b
    DO t=1,nt
      pwx1 = (h_capital(1:nx, t)+h_capital(2:nx+1, t))/2
      pwy1 = n + 2
      pwr1 = pwx1**pwy1
      pwx2 = (h(2:nx+1, t)-h(1:nx, t))/dx
      pwy2 = n - 1
      pwr2 = pwx2**pwy2
      d(:) = c*pwr1*pwr2
      phi(:) = -(d(:)*(h(2:nx+1, t)-h(1:nx, t))/dx)
      h(2:nx, t+1) = h(2:nx, t) + m(2:nx)*dt - dt/dx*(phi(2:nx)-phi(1:nx&
&       -1))
      WHERE (h(:, t+1) .LT. b) h(:, t+1) = b
      h_capital(:, t+1) = h(:, t+1) - b
    END DO
    v = 0.
    DO i=1,SIZE(h_capital(:, nt+1))
      v = v + h_capital(i, nt+1)*dx
    END DO
  END SUBROUTINE FORWARD_PROBLEM

END MODULE FORWARD_DIFF

